export enum AuthorizeActionTypes {
  AUTHORIZE_USER_SUCCESS = 'AUTHORIZE_USER_SUCCESS',
  AUTHORIZE_USER = 'AUTHORIZE_USER',
  AUTHORIZE_USER_ERROR = 'AUTHORIZE_USER_ERROR',
}

export enum RegisterActionTypes {
  REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS',
  REGISTER_USER = 'REGISTER_USER',
  REGISTER_USER_ERROR = 'REGISTER_USER_ERROR',
}

export enum GetCurrentUserActionTypes {
  GET_CURRENT_USER = 'GET_CURRENT_USER',
  GET_CURRENT_USER_ERROR = 'GET_CURRENT_USER_ERROR',
  GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS',
}

export enum EditUserActionTypes {
  EDIT_USER_DATA = 'EDIT_USER_DATA',
  EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS',
  EDIT_USER_FAILED = 'EDIT_USER_FAILED',
}

export enum ConfirmUserActionTypes {
  CONFIRM_USER = 'CONFIRM_USER',
  CONFIRM_USER_SUCCESS = 'CONFIRM_USER_SUCCESS',
  CONFIRM_USER_ERROR = 'CONFIRM_USER_ERROR',
}

export enum LogoutActionType {
  LOGOUT_USER = 'LOGOUT_USER',
}

export enum AddEventInCalendarActionTypes {
  ADD_EVENT_IN_CALENDAR_SUCCESS = 'ADD_EVENT_IN_CALENDAR_SUCCESS',
  ADD_EVENT_IN_CALENDAR_ERROR = 'ADD_EVENT_IN_CALENDAR_ERROR',
  ADD_EVENT_IN_CALENDAR = 'ADD_EVENT_IN_CALENDAR',
  CLOSE_NOTIFICATION = 'CLOSE_NOTIFICATION',
}

export enum LoadEventsActionTypes {
  LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS',
  LOAD_EVENTS_ERROR = 'LOAD_EVENTS_ERROR',
  LOAD_EVENTS = 'LOAD_EVENTS',
}

export enum SubscribeToNotificationsActionTypes {
  SUBSCRIBE_TO_NOTIFICATIONS = 'SUBSCRIBE_TO_NOTIFICATIONS',
  SUBSCRIBE_TO_NOTIFICATIONS_ERROR = 'SUBSCRIBE_TO_NOTIFICATIONS_ERROR',
  SUBSCRIBE_TO_NOTIFICATIONS_SUCCESS = 'SUBSCRIBE_TO_NOTIFICATIONS_SUCCESS',
}

export enum SendEmailForPasswordResetActionTypes {
  SEND_EMAIL_FOR_PASSWORD_RESET = 'SEND_EMAIL_FOR_PASSWORD_RESET',
  SEND_EMAIL_FOR_PASSWORD_RESET_ERROR = 'SEND_EMAIL_FOR_PASSWORD_RESET_ERROR',
  SEND_EMAIL_FOR_PASSWORD_RESET_SUCCESS = 'SEND_EMAIL_FOR_PASSWORD_RESET_SUCCESS',
}

export enum ResetPasswordActionTypes {
  RESET_PASSWORD = 'RESET_PASSWORD',
  RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR',
  RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS',
}

export enum LoadMapEventsActionTypes {
  LOAD_MAP_EVENTS_SUCCESS = 'LOAD_MAP_EVENTS_SUCCESS',
  LOAD_MAP_EVENTS_ERROR = 'LOAD_MAP_EVENTS_ERROR',
  LOAD_MAP_EVENTS = 'LOAD_MAP_EVENTS',
}

export enum LoadEventsCategoryActionTypes {
  LOAD_EVENTS_CATEGORY_SUCCESS = 'LOAD_EVENTS_CATEGORY_SUCCESS',
  LOAD_EVENTS_CATEGORY_ERROR = 'LOAD_EVENTS_CATEGORY_ERROR',
  LOAD_EVENTS_CATEGORY = 'LOAD_EVENTS_CATEGORY',
}

export enum LoadSearchedEventsActionTypes {
  LOAD_SEARCHED_EVENTS_SUCCESS = 'LOAD_SEARCHED_EVENTS_SUCCESS',
  LOAD_SEARCHED_EVENTS_ERROR = 'LOAD_SEARCHED_EVENTS_ERROR',
  LOAD_SEARCHED_EVENTS = 'LOAD_SEARCHED_EVENTS',
}

export enum GetUserLocationActionTypes {
  GET_USER_LOCATION = 'GET_USER_LOCATION',
  GET_USER_LOCATION_ERROR = 'GET_USER_LOCATION_ERROR',
  GET_USER_LOCATION_SUCCESS = 'GET_USER_LOCATION_SUCCESS',
}

export enum ChangeUserLocationActionTypes {
  CHANGE_USER_LOCATION = 'CHANGE_USER_LOCATION',
  CHANGE_USER_LOCATION_ERROR = 'CHANGE_USER_LOCATION_ERROR',
  CHANGE_USER_LOCATION_SUCCESS = 'CHANGE_USER_LOCATION_SUCCESS',
}

export enum LoadProfileEventsActionTypes {
  LOAD_PROFILE_EVENTS = 'LOAD_PROFILE_EVENTS',
  LOAD_PROFILE_EVENTS_SUCCESS = 'LOAD_PROFILE_EVENTS_SUCCESS',
  LOAD_PROFILE_EVENTS_ERROR = 'LOAD_PROFILE_EVENTS_ERROR',
}

export enum LoadEventActionTypes {
  LOAD_EVENT = 'LOAD_EVENT',
  LOAD_EVENT_SUCCESS = 'LOAD_EVENT_SUCCESS',
  LOAD_EVENT_ERROR = 'LOAD_EVENT_ERROR',
}

export enum CreatePaymentSessionActionTypes {
  CREATE_PAYMENT_SESSION = 'CREATE_PAYMENT_SESSION',
  CREATE_PAYMENT_SESSION_ERROR = 'CREATE_PAYMENT_SESSION_ERROR',
  CREATE_PAYMENT_SESSION_SUCCESS = 'CREATE_PAYMENT_SESSION_SUCCESS',
}

export enum SubscribeToNewslettersActionTypes {
  SUBSCRIBE_TO_NEWSLETTERS = 'SUBSCRIBE_TO_NEWSLETTERS',
  SUBSCRIBE_TO_NEWSLETTERS_ERROR = 'SUBSCRIBE_TO_NEWSLETTERS_ERROR',
  SUBSCRIBE_TO_NEWSLETTERS_SUCCESS = 'SUBSCRIBE_TO_NEWSLETTERS_SUCCESS',
}

export enum ConfirmEventsBookingActionTypes {
  CONFIRM_EVENTS_BOOKING = 'CONFIRM_EVENTS_BOOKING',
  CONFIRM_EVENTS_BOOKING_ERROR = 'CONFIRM_EVENTS_BOOKING_ERROR',
  CONFIRM_EVENTS_BOOKING_SUCCESS = 'CONFIRM_EVENTS_BOOKING_SUCCESS',
}

export enum AddEventActionTypes {
  ADD_EVENT = 'ADD_EVENT',
  ADD_EVENT_ERROR = 'ADD_EVENT_ERROR',
  ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS',
}

export enum EditEventActionTypes {
  EDIT_EVENT = 'EDIT_EVENT',
  EDIT_EVENT_ERROR = 'EDIT_EVENT_ERROR',
  EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS',
}

export enum CreateAdvertisementPaymentActionTypes {
  CREATE_ADVERTISEMENT_PAYMENT = 'CREATE_ADVERTISEMENT_PAYMENT',
  CREATE_ADVERTISEMENT_PAYMENT_ERROR = 'CREATE_ADVERTISEMENT_PAYMENT_ERROR',
  CREATE_ADVERTISEMENT_PAYMENT_SUCCESS = 'CREATE_ADVERTISEMENT_PAYMENT_SUCCESS',
}

export enum ConfirmEventAdvertisementActionTypes {
  CONFIRM_EVENT_ADVERTISEMENT = 'CONFIRM_EVENT_ADVERTISEMENT',
  CONFIRM_EVENT_ADVERTISEMENT_ERROR = 'CONFIRM_EVENT_ADVERTISEMENT_ERROR',
  CONFIRM_EVENT_ADVERTISEMENT_SUCCESS = 'CONFIRM_EVENT_ADVERTISEMENT_SUCCESS',
}

export enum LoadUnapprovedEventsActionTypes {
  LOAD_UNNAPROVED_EVENTS = 'LOAD_UNAPPROVED_EVENTS',
  LOAD_UNNAPROVED_EVENTS_ERROR = 'LOAD_UNNAPROVED_EVENTS_ERROR',
  LOAD_UNNAPROVED_EVENTS_SUCCESS = 'LOAD_UNNAPROVED_EVENTS_SUCCESS',
}

export enum ApproveEventActionTypes {
  APPROVE_EVENT = 'APPROVE_EVENT',
  APPROVE_EVENT_ERROR = 'APPROVE_EVENT_ERROR',
  APPROVE_EVENT_SUCCESS = 'APPROVE_EVENT_SUCCESS',
}

export enum DeleteEventActionTypes {
  DELETE_EVENT = 'DELETE_EVENT',
  DELETE_EVENT_ERROR = 'DELETE_EVENT_ERROR',
  DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS',
}

export enum LoadClientsActionTypes {
  LOAD_CLIENTS = 'LOAD_CLIENTS',
  LOAD_CLIENTS_ERROR = 'LOAD_CLIENTS_ERROR',
  LOAD_CLIENTS_SUCCESS = 'LOAD_CLIENTS_SUCCESS',
}

export enum LoadClientActionTypes {
  LOAD_CLIENT = 'LOAD_CLIENT',
  LOAD_CLIENT_ERROR = 'LOAD_CLIENT_ERROR',
  LOAD_CLIENT_SUCCESS = 'LOAD_CLIENT_SUCCESS',
}

export enum LoadClientEventsActionTypes {
  LOAD_CLIENT_EVENTS = 'LOAD_CLIENT_EVENTS',
  LOAD_CLIENT_EVENTS_ERROR = 'LOAD_CLIENT_EVENTS_ERROR',
  LOAD_CLIENT_EVENTS_SUCCESS = 'LOAD_CLIENT_EVENTS_SUCCESS',
}

export enum EditClientActionTypes {
  EDIT_CLIENT = 'EDIT_CLIENT',
  EDIT_CLIENT_ERROR = 'EDIT_CLIENT_ERROR',
  EDIT_CLIENT_SUCCESS = 'EDIT_CLIENT_SUCCESS',
}

export enum BlockClientActionTypes {
  BLOCK_CLIENT = 'BLOCK_CLIENT',
  BLOCK_CLIENT_ERROR = 'BLOCK_CLIENT_ERROR',
  BLOCK_CLIENT_SUCCESS = 'BLOCK_CLIENT_SUCCESS',
}

export enum GetUserCategoriesActionTypes {
  GET_USER_CATEGORIES = 'GET_USER_CATEGORIES',
  GET_USER_CATEGORIES_ERROR = 'GET_USER_CATEGORIES_ERROR',
  GET_USER_CATEGORIES_SUCCESS = 'GET_USER_CATEGORIES_SUCCESS',
}

export enum CloseAlertActionType {
  CLOSE_ALERT = 'CLOSE_ALERT',
}

export enum ImportNewClientsActionTypes {
  IMPORT_NEW_CLIENTS = 'IMPORT_NEW_CLIENTS',
  IMPORT_NEW_CLIENTS_ERROR = 'IMPORT_NEW_CLIENTS_ERROR',
  IMPORT_NEW_CLIENTS_SUCCESS = 'IMPORT_NEW_CLIENTS_SUCCESS',
}
